package com.palette.busi.project.tms.core.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.annotations.ResultType;

import com.palette.busi.project.tms.core.entity.TmConsignment;
import com.palette.busi.project.tms.core.dao.TmConsignmentSqlProvider;
import com.palette.busi.project.tms.core.base.BaseMybatisMapper;

public interface TmConsignmentIntf extends BaseMybatisMapper {


	@Select("SELECT  TM_CONSIGNMENT_ID  AS tmConsignmentId, CONSIGNMENT_NO  AS consignmentNo, MEMBER_CODE  AS memberCode, IDCARD_NO  AS idcardNo, IDCARD_FULL_NAME  AS idcardFullName, IDCARD_ADDRESS  AS idcardAddress, SHIPPER_MEMBER_CODE  AS shipperMemberCode, SHIPPER_NAME  AS shipperName, SHIPPER_COMPANY_NAME  AS shipperCompanyName, SHIPPER_COUNTRY_CODE  AS shipperCountryCode, SHIPPER_STATE_CODE  AS shipperStateCode, SHIPPER_CITY_CODE  AS shipperCityCode, SHIPPER_POST_CODE  AS shipperPostCode, SHIPPER_STREET  AS shipperStreet, SHIPPER_MOBILE_NO  AS shipperMobileNo, SHIPPER_PHONE_NO  AS shipperPhoneNo, SHIPPER_OTHER_CONTACT_NO  AS shipperOtherContactNo, SHIPPER_CHINESE_FULL_ADDRESS  AS shipperChineseFullAddress, SHIPPER_ENGLISH_FULL_ADDRESS  AS shipperEnglishFullAddress, CONSIGNEE_NAME  AS consigneeName, CONSIGNEE_COMPANY_NAME  AS consigneeCompanyName, CONSIGNEE_COUNTRY_CODE  AS consigneeCountryCode, CONSIGNEE_STATE_CODE  AS consigneeStateCode, CONSIGNEE_CITY_CODE  AS consigneeCityCode, CONSIGNEE_DISTRICT_CODE  AS consigneeDistrictCode, CONSIGNEE_POST_CODE  AS consigneePostCode, CONSIGNEE_STREET  AS consigneeStreet, CONSIGNEE_MOBILE_NO  AS consigneeMobileNo, CONSIGNEE_PHONE_NO  AS consigneePhoneNo, CONSIGNEE_OTHER_CONTACT_NO  AS consigneeOtherContactNo, CONSIGNEE_CHINESE_FULL_ADDRESS  AS consigneeChineseFullAddress, CONSIGNEE_ENGLISH_FULL_ADDRESS  AS consigneeEnglishFullAddress, TOTAL_GOODS_DESCRIPTION  AS totalGoodsDescription, TOTAL_GOODS_VALUE  AS totalGoodsValue, TOTAL_GOODS_VALUE_CURRENCY  AS totalGoodsValueCurrency, TOTAL_QTY  AS totalQty, TOTAL_WEIGHT  AS totalWeight, ORIG_PORT  AS origPort, DEST_PORT  AS destPort, LENGTH  AS length, WIDTH  AS width, HEIGHT  AS height, VOLUME_WEIGHT  AS volumeWeight, APPLY_WEIGHT  AS applyWeight, ACTUAL_UNIT  AS actualUnit, ACTUAL_WEIGHT  AS actualWeight, SELLER_NAME  AS sellerName, CONVERT_UNIT  AS convertUnit, SELLER_ORDER_NO  AS sellerOrderNo, LOGISTICS_VENDOR  AS logisticsVendor, LOGISTICS_NO  AS logisticsNo, WAREHOUSE_CODE  AS warehouseCode, MAWB_CODE  AS mawbCode, SECTOR_CODE  AS sectorCode, TM_SECTOR_ID  AS tmSectorId, DELIVERY_VENDOR  AS deliveryVendor, DELIVERY_NO  AS deliveryNo, TRANSFER_TYPE  AS transferType, MEMO  AS memo, CREATE_TIME  AS createTime, CR_ADDRESS_ID  AS crAddressId, ACTURAL_WAREHOUSE_CODE  AS acturalWarehouseCode, REMARK  AS remark, LOC_CODE  AS locCode, PRINCIPLE  AS principle, RECORD_VERSION  AS recordVersion, CREATE_USER_CODE  AS createUserCode, CREATE_DATE_TIME  AS createDateTime, CREATE_TIME_ZONE  AS createTimeZone, UPDATE_USER_CODE  AS updateUserCode, UPDATE_DATE_TIME  AS updateDateTime, UPDATE_TIME_ZONE  AS updateTimeZone, IDCARD_FRONT_IMG  AS idcardFrontImg, IDCARD_BACK_IMG  AS idcardBackImg, MCT_API_REQUEST_ID  AS mctApiRequestId, SOURCE_REQUEST_ID  AS sourceRequestId, DATA_SOURCE  AS dataSource, REF_LOGISTICS_NO  AS refLogisticsNo, SERVICE_PRODUCT_CODE  AS serviceProductCode FROM tm_consignment WHERE tm_consignment_id=#{tmConsignmentId}")
	public TmConsignment selectTmConsignmentById(@Param("tmConsignmentId") int tmConsignmentId);
	
	@Select("SELECT  TM_CONSIGNMENT_ID  AS tmConsignmentId, CONSIGNMENT_NO  AS consignmentNo, MEMBER_CODE  AS memberCode, IDCARD_NO  AS idcardNo, IDCARD_FULL_NAME  AS idcardFullName, IDCARD_ADDRESS  AS idcardAddress, SHIPPER_MEMBER_CODE  AS shipperMemberCode, SHIPPER_NAME  AS shipperName, SHIPPER_COMPANY_NAME  AS shipperCompanyName, SHIPPER_COUNTRY_CODE  AS shipperCountryCode, SHIPPER_STATE_CODE  AS shipperStateCode, SHIPPER_CITY_CODE  AS shipperCityCode, SHIPPER_POST_CODE  AS shipperPostCode, SHIPPER_STREET  AS shipperStreet, SHIPPER_MOBILE_NO  AS shipperMobileNo, SHIPPER_PHONE_NO  AS shipperPhoneNo, SHIPPER_OTHER_CONTACT_NO  AS shipperOtherContactNo, SHIPPER_CHINESE_FULL_ADDRESS  AS shipperChineseFullAddress, SHIPPER_ENGLISH_FULL_ADDRESS  AS shipperEnglishFullAddress, CONSIGNEE_NAME  AS consigneeName, CONSIGNEE_COMPANY_NAME  AS consigneeCompanyName, CONSIGNEE_COUNTRY_CODE  AS consigneeCountryCode, CONSIGNEE_STATE_CODE  AS consigneeStateCode, CONSIGNEE_CITY_CODE  AS consigneeCityCode, CONSIGNEE_DISTRICT_CODE  AS consigneeDistrictCode, CONSIGNEE_POST_CODE  AS consigneePostCode, CONSIGNEE_STREET  AS consigneeStreet, CONSIGNEE_MOBILE_NO  AS consigneeMobileNo, CONSIGNEE_PHONE_NO  AS consigneePhoneNo, CONSIGNEE_OTHER_CONTACT_NO  AS consigneeOtherContactNo, CONSIGNEE_CHINESE_FULL_ADDRESS  AS consigneeChineseFullAddress, CONSIGNEE_ENGLISH_FULL_ADDRESS  AS consigneeEnglishFullAddress, TOTAL_GOODS_DESCRIPTION  AS totalGoodsDescription, TOTAL_GOODS_VALUE  AS totalGoodsValue, TOTAL_GOODS_VALUE_CURRENCY  AS totalGoodsValueCurrency, TOTAL_QTY  AS totalQty, TOTAL_WEIGHT  AS totalWeight, ORIG_PORT  AS origPort, DEST_PORT  AS destPort, LENGTH  AS length, WIDTH  AS width, HEIGHT  AS height, VOLUME_WEIGHT  AS volumeWeight, APPLY_WEIGHT  AS applyWeight, ACTUAL_UNIT  AS actualUnit, ACTUAL_WEIGHT  AS actualWeight, SELLER_NAME  AS sellerName, CONVERT_UNIT  AS convertUnit, SELLER_ORDER_NO  AS sellerOrderNo, LOGISTICS_VENDOR  AS logisticsVendor, LOGISTICS_NO  AS logisticsNo, WAREHOUSE_CODE  AS warehouseCode, MAWB_CODE  AS mawbCode, SECTOR_CODE  AS sectorCode, TM_SECTOR_ID  AS tmSectorId, DELIVERY_VENDOR  AS deliveryVendor, DELIVERY_NO  AS deliveryNo, TRANSFER_TYPE  AS transferType, MEMO  AS memo, CREATE_TIME  AS createTime, CR_ADDRESS_ID  AS crAddressId, ACTURAL_WAREHOUSE_CODE  AS acturalWarehouseCode, REMARK  AS remark, LOC_CODE  AS locCode, PRINCIPLE  AS principle, RECORD_VERSION  AS recordVersion, CREATE_USER_CODE  AS createUserCode, CREATE_DATE_TIME  AS createDateTime, CREATE_TIME_ZONE  AS createTimeZone, UPDATE_USER_CODE  AS updateUserCode, UPDATE_DATE_TIME  AS updateDateTime, UPDATE_TIME_ZONE  AS updateTimeZone, IDCARD_FRONT_IMG  AS idcardFrontImg, IDCARD_BACK_IMG  AS idcardBackImg, MCT_API_REQUEST_ID  AS mctApiRequestId, SOURCE_REQUEST_ID  AS sourceRequestId, DATA_SOURCE  AS dataSource, REF_LOGISTICS_NO  AS refLogisticsNo, SERVICE_PRODUCT_CODE  AS serviceProductCode FROM tm_consignment")
	public List<TmConsignment> selectAllTmConsignment();
	
	@Insert("insert into tm_consignment ( TM_CONSIGNMENT_ID, CONSIGNMENT_NO, MEMBER_CODE, IDCARD_NO, IDCARD_FULL_NAME, IDCARD_ADDRESS, SHIPPER_MEMBER_CODE, SHIPPER_NAME, SHIPPER_COMPANY_NAME, SHIPPER_COUNTRY_CODE, SHIPPER_STATE_CODE, SHIPPER_CITY_CODE, SHIPPER_POST_CODE, SHIPPER_STREET, SHIPPER_MOBILE_NO, SHIPPER_PHONE_NO, SHIPPER_OTHER_CONTACT_NO, SHIPPER_CHINESE_FULL_ADDRESS, SHIPPER_ENGLISH_FULL_ADDRESS, CONSIGNEE_NAME, CONSIGNEE_COMPANY_NAME, CONSIGNEE_COUNTRY_CODE, CONSIGNEE_STATE_CODE, CONSIGNEE_CITY_CODE, CONSIGNEE_DISTRICT_CODE, CONSIGNEE_POST_CODE, CONSIGNEE_STREET, CONSIGNEE_MOBILE_NO, CONSIGNEE_PHONE_NO, CONSIGNEE_OTHER_CONTACT_NO, CONSIGNEE_CHINESE_FULL_ADDRESS, CONSIGNEE_ENGLISH_FULL_ADDRESS, TOTAL_GOODS_DESCRIPTION, TOTAL_GOODS_VALUE, TOTAL_GOODS_VALUE_CURRENCY, TOTAL_QTY, TOTAL_WEIGHT, ORIG_PORT, DEST_PORT, LENGTH, WIDTH, HEIGHT, VOLUME_WEIGHT, APPLY_WEIGHT, ACTUAL_UNIT, ACTUAL_WEIGHT, SELLER_NAME, CONVERT_UNIT, SELLER_ORDER_NO, LOGISTICS_VENDOR, LOGISTICS_NO, WAREHOUSE_CODE, MAWB_CODE, SECTOR_CODE, TM_SECTOR_ID, DELIVERY_VENDOR, DELIVERY_NO, TRANSFER_TYPE, MEMO, CREATE_TIME, CR_ADDRESS_ID, ACTURAL_WAREHOUSE_CODE, REMARK, LOC_CODE, PRINCIPLE, RECORD_VERSION, CREATE_USER_CODE, CREATE_DATE_TIME, CREATE_TIME_ZONE, UPDATE_USER_CODE, UPDATE_DATE_TIME, UPDATE_TIME_ZONE, IDCARD_FRONT_IMG, IDCARD_BACK_IMG, MCT_API_REQUEST_ID, SOURCE_REQUEST_ID, DATA_SOURCE, REF_LOGISTICS_NO, SERVICE_PRODUCT_CODE ) values (#{tmConsignmentId},#{consignmentNo},#{memberCode},#{idcardNo},#{idcardFullName},#{idcardAddress},#{shipperMemberCode},#{shipperName},#{shipperCompanyName},#{shipperCountryCode},#{shipperStateCode},#{shipperCityCode},#{shipperPostCode},#{shipperStreet},#{shipperMobileNo},#{shipperPhoneNo},#{shipperOtherContactNo},#{shipperChineseFullAddress},#{shipperEnglishFullAddress},#{consigneeName},#{consigneeCompanyName},#{consigneeCountryCode},#{consigneeStateCode},#{consigneeCityCode},#{consigneeDistrictCode},#{consigneePostCode},#{consigneeStreet},#{consigneeMobileNo},#{consigneePhoneNo},#{consigneeOtherContactNo},#{consigneeChineseFullAddress},#{consigneeEnglishFullAddress},#{totalGoodsDescription},#{totalGoodsValue},#{totalGoodsValueCurrency},#{totalQty},#{totalWeight},#{origPort},#{destPort},#{length},#{width},#{height},#{volumeWeight},#{applyWeight},#{actualUnit},#{actualWeight},#{sellerName},#{convertUnit},#{sellerOrderNo},#{logisticsVendor},#{logisticsNo},#{warehouseCode},#{mawbCode},#{sectorCode},#{tmSectorId},#{deliveryVendor},#{deliveryNo},#{transferType},#{memo},#{createTime},#{crAddressId},#{acturalWarehouseCode},#{remark},#{locCode},#{principle},#{recordVersion},#{createUserCode},#{createDateTime},#{createTimeZone},#{updateUserCode},#{updateDateTime},#{updateTimeZone},#{idcardFrontImg},#{idcardBackImg},#{mctApiRequestId},#{sourceRequestId},#{dataSource},#{refLogisticsNo},#{serviceProductCode})")
	public int insertTmConsignment(TmConsignment tmConsignment);

	@UpdateProvider(type=TmConsignmentSqlProvider.class, method="update")
	public int updateTmConsignment(TmConsignment tmConsignment);
	
	@Delete("delete from tm_consignment where tm_consignment_id = #{tmConsignmentId}")
	public int deleteTmConsignment(@Param("tmConsignmentId") int tmConsignmentId);

    @SelectProvider(type=TmConsignmentSqlProvider.class, method="selectAllByRecord")
    @ResultType(TmConsignment.class)
    public List<TmConsignment> selectAllByRecord(TmConsignment record);
    
}